accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.Signup.as_view(), name='signup'),

    path('change-password/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view() ,name='password_change_done'),
]

admins/urls.py
from django.urls import path

from .import views

app_name = 'admins'

urlpatterns = [
    path('admin/', views.dashboard, name='dashboard'),
    path('create-school/', views.create_edit_school, name='create_school'),
    path('edit-school/<int:id>/', views.create_edit_school, name='edit_school'),
    path('list-schools/', views.list_school, name='list_school'),
    path('school/<int:pk>/delete/', views.SchoolDeleteView.as_view(), name='school_delete'),

    # path('results/<int:school_id>/', views.get_exam_rank, name='results'),

    path('subject-list/', views.SubjectGroupList.as_view(), name='subject_list'),
    path('create-subject/', views.SubjectCreateView.as_view(), name='create_subject'),
    path('update-subject/<int:pk>', views.SubjectUpdateView.as_view(), name='update_subject'),
    path('delete-subject/<int:pk>', views.SubjectDeleteView.as_view(), name='delete_subject'),

    path('combination-list/', views.CombinationList.as_view(), name='combination_list'),
    path('create-combination/', views.CombinationCreateView.as_view(), name='create_combination'),
    path('update-combination/<int:pk>', views.CombinationUpdateView.as_view(), name='update_combination'),
    path('delete-combination/<int:pk>', views.CombinationDeleteView.as_view(), name='delete_combination'),
    path('search-result/', views.search_school_results, name='search_result'),
    path('more-info-request/', views.more_info_request, name='more_info_request'),
    path('read-school/<int:pk>', views.SchoolReadView.as_view(), name='read_school'),
    path('read-search/<int:pk>', views.SearchReadView.as_view(), name='read_search'),
    path('change-request-status/<int:id>/', views.change_request_status, name='change_request_status')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('admins.urls', namespace='admins')),
    path('location/', include('location.urls', namespace='location'))
]

location/urls.py
from django.urls import path

from .import views

app_name = 'location'

urlpatterns = [
    path('import-region/', views.import_region, name='import_region'),
    path('import-district/', views.import_district, name='import_district'),
    path('ajax/load-district/', views.load_district, name='ajax_load_district'),
]

main/urls.py
from django.urls import path

from .import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('school-search-result/', views.school_list, name='school_list'),
    path('subscribe/', views.SubscribeCreateView.as_view(), name='subscribe'),
]

templates/dashboard/includes/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <strong>Copyright &copy;  <script>document.write(new Date().getFullYear())</script> <a href="#">School Directives</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 1.0.0
    </div>
</footer>

templates/dashboard/includes/navbar.html
    {% load static %}
    <!-- Navbar -->
	<nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom border-5 border-primary">
		<!-- Left navbar links -->
		<ul class="navbar-nav">
		<li class="nav-item">
			<a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
		</li>
		<li class="nav-item d-none d-sm-inline-block">
			<a href="/" class="nav-link">Home</a>
		</li>
		</ul>

		<!-- Right navbar links -->
		<ul class="navbar-nav ml-auto">
		<li class="nav-item">
			<a class="nav-link" href="{% url 'accounts:logout' %}">
			<i class="fas fa-sign-out-alt" style="font-size: 22px;"></i>
			</a>
		</li>
		</ul>
	</nav>
	<!-- /.navbar -->

templates/dashboard/includes/scripts.html
    {% load static %}
    <!-- REQUIRED SCRIPTS -->
	<!-- jQuery -->
	<script src="{% static 'dashboard/plugins/jquery/jquery.min.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
	<!-- overlayScrollbars -->
	<script src="{% static 'dashboard/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
	<!-- AdminLTE App -->
	<script src="{% static 'dashboard/js/adminlte.js' %}"></script>
	<!-- Select2 -->
	<script src="{% static 'dashboard/plugins/select2/js/select2.full.min.js' %}"></script>
	<!-- DataTables  & Plugins -->
	<script src="{% static 'dashboard/plugins/datatables/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'dashboard/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
	<script src="{% static 'dashboard/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
	<script src="{% static 'dashboard/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
	<script src="{% static 'dashboard/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
	<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
	<script src="{% static 'dashboard/plugins/jszip/jszip.min.js' %}"></script>
	<script src="{% static 'dashboard/plugins/pdfmake/pdfmake.min.js' %}"></script>
	<script src="{% static 'dashboard/plugins/pdfmake/vfs_fonts.js' %}"></script>
	<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
	<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
	<script src="{% static 'dashboard/plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
	
	<script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
	<script src="{% static 'dashboard/js/toastr.min.js' %}"></script>

	<script>
		{% if messages %}
			document.addEventListener("DOMContentLoaded", function(event) {
				toastr.options = { "closeButton": true, "debug": false, "newestOnTop": true,
					"progressBar": false, "positionClass": "toast-top-right", "preventDuplicates": true,
					"onclick": null, "showDuration": "300", "hideDuration": "1000", "timeOut": "5000",
					"extendedTimeOut": "1000", "showEasing": "swing", "hideEasing": "linear",
					"showMethod": "fadeIn", "hideMethod": "fadeOut" };
				{% autoescape off %}
					{% for msg in messages %}
						toastr.{{ msg.level_tag }}("{{ msg }}");
					{% endfor %}
				{% endautoescape %}
			});
		{% endif %}
	</script>
    
	
	<script>
		$(function () {
		  //Initialize Select2 Elements
		  $('.select2').select2()
	  
		  //Initialize Select2 Elements
		  $('.select2bs4').select2({
			theme: 'bootstrap4'
		  })
	  
		  //Datemask dd/mm/yyyy
		  $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
		  //Datemask2 mm/dd/yyyy
		  $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
		  //Money Euro
		  $('[data-mask]').inputmask()
	  
		  //Date range picker
		  $('#reservationdate').datetimepicker({
			  format: 'L'
		  });
		  //Date range picker
		  $('#reservation').daterangepicker()
		  //Date range picker with time picker
		  $('#reservationtime').daterangepicker({
			timePicker: true,
			timePickerIncrement: 30,
			locale: {
			  format: 'MM/DD/YYYY hh:mm A'
			}
		  })
		  //Date range as a button
		  $('#daterange-btn').daterangepicker(
			{
			  ranges   : {
				'Today'       : [moment(), moment()],
				'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
				'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
				'Last 30 Days': [moment().subtract(29, 'days'), moment()],
				'This Month'  : [moment().startOf('month'), moment().endOf('month')],
				'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
			  },
			  startDate: moment().subtract(29, 'days'),
			  endDate  : moment()
			},
			function (start, end) {
			  $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
			}
		  )
	  
		  //Timepicker
		  $('#timepicker').datetimepicker({
			format: 'LT'
		  })
	  
		  //Bootstrap Duallistbox
		  $('.duallistbox').bootstrapDualListbox()
	  
		  //Colorpicker
		  $('.my-colorpicker1').colorpicker()
		  //color picker with addon
		  $('.my-colorpicker2').colorpicker()
	  
		  $('.my-colorpicker2').on('colorpickerChange', function(event) {
			$('.my-colorpicker2 .fa-square').css('color', event.color.toString());
		  });
	  
		  $("input[data-bootstrap-switch]").each(function(){
			$(this).bootstrapSwitch('state', $(this).prop('checked'));
		  });
	  
		})
		// BS-Stepper Init
		document.addEventListener('DOMContentLoaded', function () {
		  window.stepper = new Stepper(document.querySelector('.bs-stepper'))
		});
	  
		// DropzoneJS Demo Code Start
		Dropzone.autoDiscover = false;
	  
		// Get the template HTML and remove it from the doumenthe template HTML and remove it from the doument
		var previewNode = document.querySelector("#template");
		previewNode.id = "";
		var previewTemplate = previewNode.parentNode.innerHTML;
		previewNode.parentNode.removeChild(previewNode);
	  
		var myDropzone = new Dropzone(document.body, { // Make the whole body a dropzone
		  url: "/target-url", // Set the url
		  thumbnailWidth: 80,
		  thumbnailHeight: 80,
		  parallelUploads: 20,
		  previewTemplate: previewTemplate,
		  autoQueue: false, // Make sure the files aren't queued until manually added
		  previewsContainer: "#previews", // Define the container to display the previews
		  clickable: ".fileinput-button" // Define the element that should be used as click trigger to select files.
		});
	  
		myDropzone.on("addedfile", function(file) {
		  // Hookup the start button
		  file.previewElement.querySelector(".start").onclick = function() { myDropzone.enqueueFile(file); };
		});
	  
		// Update the total progress bar
		myDropzone.on("totaluploadprogress", function(progress) {
		  document.querySelector("#total-progress .progress-bar").style.width = progress + "%";
		});
	  
		myDropzone.on("sending", function(file) {
		  // Show the total progress bar when upload starts
		  document.querySelector("#total-progress").style.opacity = "1";
		  // And disable the start button
		  file.previewElement.querySelector(".start").setAttribute("disabled", "disabled");
		});
	  
		// Hide the total progress bar when nothing's uploading anymore
		myDropzone.on("queuecomplete", function(progress) {
		  document.querySelector("#total-progress").style.opacity = "0";
		});
	  
		// Setup the buttons for all transfers
		// The "add files" button doesn't need to be setup because the config
		// `clickable` has already been specified.
		document.querySelector("#actions .start").onclick = function() {
		  myDropzone.enqueueFiles(myDropzone.getFilesWithStatus(Dropzone.ADDED));
		};
		document.querySelector("#actions .cancel").onclick = function() {
		  myDropzone.removeAllFiles(true);
		};
		// DropzoneJS Demo Code End
	  </script>

templates/dashboard/includes/sidebar.html
    {% load static %}
	{% load active_link_tags %}
    <!-- Main Sidebar Container -->
	<aside class="main-sidebar sidebar-dark-primary elevation-4">
		<!-- Brand Logo -->
		<a href="/" class="brand-link">
		<img src="{% static 'main/images/logo.jpg' %}" alt="logo" class="brand-image img-circle elevation-3" style="opacity: .8">
		<span class="brand-text font-weight-light">Admin Panel</span>
		</a>

		<!-- Sidebar -->
		<div class="sidebar">

			<!-- Sidebar user panel (optional) -->
			<div class="user-panel mt-3 pb-3 mb-3 d-flex">
				<div class="image">
				  <img src="{% static 'dashboard/img/profile.png' %}" class="img-circle elevation-2" alt="User Image">
				</div>
				<div class="info">
				  <a href="#" class="d-block">{{user.username}}</a>
				</div>
			  </div>

			<nav class="mt-2">
				<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
					
					<li class="nav-item">
						<a href="{% url 'admins:dashboard' %}" class="nav-link {% active_link 'admins:dashboard' 'active' %}">
						<i class="nav-icon fas fa-tachometer-alt"></i>
						<p>Dashboard</p></a>
					</li>
					<li class="nav-item">
						<a href="{% url 'admins:more_info_request' %}" class="nav-link {% active_link 'admins:more_info_request' 'active' %}">
							<i class="nav-icon fas fa-info-circle"></i>
						<p>More Info Request</p>
						</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'admins:search_result' %}" class="nav-link {% active_link 'admins:search_result' 'active' %}">
						<i class="nav-icon fas fa-search"></i>
						<p>Search Results</p></a>
					</li>

					<li class="nav-item">
						<a href="{% url 'admins:list_school' %}" class="nav-link {% active_link 'admins:list_school' 'active' %}">
						<i class="nav-icon fas fa-th-large"></i>
						<p>All School</p></a>
					</li>
					<li class="nav-item">
						<a href="{% url 'admins:create_school' %}" class="nav-link {% active_link 'admins:create_school' 'active' %}">
							<i class="nav-icon fas fa-plus-square"></i>
							<p> Add School</p></a>
					</li>
					<li class="nav-item">
						<a href="{% url 'admins:subject_list' %}" class="nav-link {% active_link 'admins:subject_list' 'active' %}">
						<i class="nav-icon fas fa-chalkboard"></i>
						<p>Subject Groups</p></a>
					</li>
					<li class="nav-item">
						<a href="{% url 'admins:combination_list' %}" class="nav-link {% active_link 'admins:combination_list' 'active' %}">
						<i class="nav-icon fas fa-book"></i>
						<p>Combinations</p></a>
					</li>
					<li class="nav-item">
						<a href="{% url 'location:import_region' %}" class="nav-link {% active_link 'location:import_region' 'active' %}">
						<i class="nav-icon fas fa-file-import"></i>
						<p>Import Region</p></a>
					</li>
					<li class="nav-item">
						<a href="{% url 'location:import_district' %}" class="nav-link {% active_link 'location:import_district' 'active' %}">
						<i class="nav-icon fas fa-upload"></i>
						<p>Import District</p></a>
					</li>
					<li class="nav-item">
						<a href="{% url 'accounts:logout' %}" class="nav-link {% active_link 'accounts:logout' 'active' %}">
						<i class="nav-icon fas fa-sign-out-alt"></i>
						<p>Logout</p></a>
					</li>

				</ul>
			</nav>
		</div>
	</aside>