admins/urls.py
from django.urls import path

from .import views

app_name = 'admins'

urlpatterns = [
    path('admin/', views.dashboard, name='dashboard'),
    path('create-school/', views.create_edit_school, name='create_school'),
    path('edit-school/<int:id>/', views.create_edit_school, name='edit_school'),
    path('list-schools/', views.list_school, name='list_school'),
    path('school/<int:pk>/delete/', views.SchoolDeleteView.as_view(), name='school_delete'),

    # path('results/<int:school_id>/', views.get_exam_rank, name='results'),

    path('subject-list/', views.SubjectGroupList.as_view(), name='subject_list'),
    path('create-subject/', views.SubjectCreateView.as_view(), name='create_subject'),
    path('update-subject/<int:pk>', views.SubjectUpdateView.as_view(), name='update_subject'),
    path('delete-subject/<int:pk>', views.SubjectDeleteView.as_view(), name='delete_subject'),

    path('combination-list/', views.CombinationList.as_view(), name='combination_list'),
    path('create-combination/', views.CombinationCreateView.as_view(), name='create_combination'),
    path('update-combination/<int:pk>', views.CombinationUpdateView.as_view(), name='update_combination'),
    path('delete-combination/<int:pk>', views.CombinationDeleteView.as_view(), name='delete_combination'),
    path('search-result/', views.search_school_results, name='search_result'),
    path('more-info-request/', views.more_info_request, name='more_info_request'),
    path('read-school/<int:pk>', views.SchoolReadView.as_view(), name='read_school'),
    path('read-search/<int:pk>', views.SearchReadView.as_view(), name='read_search'),
    path('change-request-status/<int:id>/', views.change_request_status, name='change_request_status')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('admins.urls', namespace='admins')),
    path('location/', include('location.urls', namespace='location'))
]

location/urls.py
from django.urls import path

from .import views

app_name = 'location'

urlpatterns = [
    path('import-region/', views.import_region, name='import_region'),
    path('import-district/', views.import_district, name='import_district'),
    path('ajax/load-district/', views.load_district, name='ajax_load_district'),
]

main/urls.py
from django.urls import path

from .import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('school-search-result/', views.school_list, name='school_list'),
    path('subscribe/', views.SubscribeCreateView.as_view(), name='subscribe'),
]

main/forms.py
import re
from django import forms
from django.forms import RadioSelect
from bootstrap_modal_forms.forms import BSModalModelForm
 
from main.models import School, Subscribe
from location.models import Region, District


class HorizontalRadioSelect(RadioSelect):
	template_name = 'admin/horizontal_radios.html'
	option_template_name = 'admin/horizontal_option.html'


GENDER = (
	('Boys', 'Boys'),
	('Girls', 'Girls'),
	('Co-ed/boys and girls', 'Co-ed/boys and girls'),
)

class FilterForm(forms.Form):
	gender = forms.ChoiceField(choices=GENDER, label='test', widget=HorizontalRadioSelect())


class SchoolForm(forms.ModelForm):
	region = forms.ModelChoiceField(Region.objects.all(), empty_label='Select Region',required=False)
	district = forms.ModelChoiceField(District.objects.none(), empty_label='Select District',required=False)

	class Meta:
		model = School
		fields = ['region','district',]

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['district'].queryset = District.objects.none()

		if 'region' in self.data:
			try:
				region_id = int(self.data.get('region'))
				self.fields['district'].queryset = District.objects.filter(region=region_id).order_by('id')
			except (ValueError, TypeError):
				pass
		elif self.instance.pk:
			self.fields['district'].queryset = self.instance.region.district_set.order_by('id')


class SubscribeForm(BSModalModelForm):

	class Meta:
		model = Subscribe
		fields = ['name','phone',]

	# def clean_phone(self):
	# 	phone = self.cleaned_data.get('phone')
	# 	x = re.search("^255[0-9]{9}$", phone)

	# 	if not x:
	# 		raise forms.ValidationError(
	# 			"Phone number must in format 255xxxxxxxxx")
	# 	return phone

admins/templates/admins/combination_list.html
{% extends 'dashboard/base.html' %}

{% block content %}

    <div class="container pt-3 pb-5">
        <div class="card">
            <div class="card-header border-bottom border-info">
                <h3 class="text-title">Combination List</h3>
            </div>
            <div class="card-body">
                <div class="float-right pb-2">
                    <button id="create-book" class="btn btn-primary btn-md" type="button" name="button"><i class="fas fa-plus-circle mr-2"></i> Create Combination</button>
                </div>
                <div id="table">
                    <table class="table table-sm table-bordered">
                        <thead class="bg-primary text-light">
                            <tr>
                                <th>No.</th>
                                <th>Combination</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in combinations %}
                            <tr>
                                <td>{{forloop.counter}}.</td>
                                <td>{{c.name}}</td>
                                <td>
                                    <button type="button" id="update-book" class="bs-modal btn btn-sm btn-primary" data-form-url="{% url 'admins:update_combination' c.pk %}">
                                        <span class="fas fa-pencil-alt"></span>
                                    </button>
                                    <button type="button" id="delete-book" class="bs-modal btn btn-sm btn-danger" data-form-url="{% url 'admins:delete_combination' c.pk %}">
                                        <span class="fa fa-trash"></span>
                                      </button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

<!-- Modal 1 with id="create-book"-->
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

<!-- Modal 2 with id="modal" -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

{% endblock %}

{% block javascript %}
<script type="text/javascript">
    $(function () {
  
      // Update, Read and Delete book buttons open modal with id="modal" (default)
      // The formURL is retrieved from the data of the element
      $(".bs-modal").each(function () {
        $(this).modalForm({
            formURL: $(this).data('form-url')
        });
      });
  
       // Create book button opens form in modal with id="create-modal"
      $("#create-book").modalForm({
          formURL: "{% url 'admins:create_combination' %}",
          modalID: "#create-modal"
      });
  
    });
  </script>
{% endblock javascript %}

admins/templates/admins/comfirm_delete.html
{% extends 'dashboard/base.html' %}

{% block content %}

    <div class='container mt-5 align-items-center text-center' style="padding-top: 80px">
        <form method="post">{% csrf_token %} 
            <h5>Are you sure you want to delete "{{ object }}"?</h5> 
            <input class="btn btn-danger mt-2" type="submit" value="Confirm"> 
        </form> 
    </div>

{% endblock %}

admins/templates/admins/create_combination.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header bg-primary text-light">
    <h4 class="modal-title">Create Combination</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Create</button>
  </div>

</form>

admins/templates/admins/create_school.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load static i18n widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %}Add school Inforrmation{% endblock %}

{% block content %}
<div class="container-fluid" style="padding-top: 40px;">
    <div class="row">
        <div class="col-md-12">
          {% include 'messages.html' %}
          <div class="card card-info">
            <div class="card-header">
              <h3 class="card-title">Add School Information</h3>
            </div>

          <div class="card-body">

            <form id="SchoolForm" method="POST" action="." enctype="multipart/form-data" data-district-url="{% url 'location:ajax_load_district' %}">{% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
              
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            <label for="">{{ form.name.label }}*</label>
                            {% render_field form.name class="form-control" placeholder=form.name.label %}
                            {% for error in form.name.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                        <div class="col-md-3">
                            <label for="">{{ form.logo.label }}*</label>
                            {% render_field form.logo class="form-control" placeholder=form.logo.label %}
                            {% for error in form.logo.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                        <div class="col-md-3">
                            <label for="">{{ form.gender.label }}*</label>
                            {% render_field form.gender class="form-control" placeholder=form.gender.label %}
                            {% for error in form.gender.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                        <div class="col-md-3">
                            <label for="">{{ form.accomodation_type.label }}*</label>
                            {% render_field form.accomodation_type class="form-control" placeholder=form.accomodation_type.label %}
                            {% for error in form.accomodation_type.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                  <div class="row">
                      <div class="col-md-3">
                          <label for="">{{ form.class_size.label }}*</label>
                          {% render_field form.class_size class="form-control" placeholder=form.class_size.label %}
                          {% for error in form.class_size.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                      </div>
                      <div class="col-md-3">
                          <label for="">{{ form.ownership.label }}*</label>
                          {% render_field form.ownership class="form-control" placeholder=form.ownership.label %}
                          {% for error in form.ownership.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                      </div>
                      <div class="col-md-3">
                          <label for="">{{ form.school_multicultural.label }}*</label>
                          {% render_field form.school_multicultural class="form-control" placeholder=form.school_multicultural.label %}
                          {% for error in form.school_multicultural.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                      </div>
                      <div class="col-md-3">
                          <label for="">{{ form.school_location.label }}*</label>
                          {% render_field form.school_location class="form-control" placeholder=form.school_location.label %}
                          {% for error in form.school_location.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                      </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="row">
                      <div class="col-md-3">
                          <label for="">{{ form.curricular_system.label }}*</label>
                          {% render_field form.curricular_system class="form-control" placeholder=form.curricular_system.label %}
                          {% for error in form.curricular_system.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                      </div>
                      <div class="col-md-3">
                        <label for="">{{ form.average_tution_fee.label }}(optional)</label>
                        {% render_field form.average_tution_fee class="form-control" placeholder=form.average_tution_fee.label %}
                        {% for error in form.average_tution_fee.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                      </div>
                      <div class="col-md-3">
                       
                      </div>

                      <div class="col-md-3">
                        
                      </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="row">
                    <div class="col-md-12">
                      <label for="">{{ form.school_subjects.label }}(Optional)</label><br>
                      {% for value, text in form.school_subjects.field.choices %}
                        <div class="form-check form-check-inline">
                          <input class="form-check-input" id="id_{{ forloop.counter0 }}" name="{{ form.school_subjects.name }}" type="checkbox" value="{{ value }}"{% if value in checked_school_subjects %} checked="checked"{% endif %}>
                          <label class="form-check-label">{{ text }}</label>
                        </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="row">
                    <div class="col-md-12">
                      <label for="">{{ form.subject_combination.label }}(optional)</label><br>
                      {% for value, text in form.subject_combination.field.choices %}
                        <div class="form-check form-check-inline">
                          <input class="form-check-input" id="id_{{ forloop.counter0 }}" name="{{ form.subject_combination.name }}" type="checkbox" value="{{ value }}"{% if value in checked_subject_combination %} checked="checked"{% endif %}>
                          <label class="form-check-label">{{ text }}</label>
                        </div>
                      {% endfor %}
                      {% for error in form.subject_combination.errors %}
                              <span class="help-block">{{ error }}</span>
                          {% endfor %}
                    </div>
                  </div>
                </div>
                
                <div class="form-group">
                  <div class="row">
                      <div class="col-md-3">
                        <label for="">{{ form.region.label }}*</label>
                        {% render_field form.region class="form-control" placeholder=form.region.label %}
                        {% for error in form.region.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="col-md-3">
                        <label for="">{{ form.district.label }}*</label>
                        {% render_field form.district class="form-control" placeholder=form.district.label %}
                        {% for error in form.district.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                    
                  </div>
                </div>
                <div class="form-group">
                  <div class="row">
                      <div class="col-md-6">
                        {{form.no_fee|as_crispy_field}}
                      </div>
                                           
                  </div>
                </div>
            

            <div class="card-header bg-info">
              <h3 class="card-title">Add Exams Results</h4>
            </div>

            
                {{ formset.management_form }}
                <fieldset>
                  {% for form in formset %}
                  <div class="row my-2 py-2 border-top myformset sanction-element">
                    <div class="col">
                      <div class="row">
                        {{ form.id  }}
                        <div class="col">
                          <div class="form-group">
                            {{ form.classe.label_tag }}
                            {% render_field form.classe class="form-control" %}
                          </div>
                        </div>
                        <div class="col">
                          <div class="form-group">
                            {{ form.year.label_tag }}
                            {% render_field form.year class="form-control" %}
                          </div>
                        </div>
                        <div class="col">
                          <div class="form-group">
                            {{ form.division_one.label_tag }}
                            {% render_field form.division_one class="form-control" %}
                          </div>
                        </div>
                        <div class="col">
                          <div class="form-group">
                            {{ form.division_two.label_tag }}
                            {% render_field form.division_two class="form-control" %}
                          </div>
                        </div>
                        <div class="col">
                          <div class="form-group">
                            {{ form.division_three.label_tag }}
                            {% render_field form.division_three class="form-control" %}
                          </div>
                        </div>
                        <div class="col">
                          <div class="form-group">
                            {{ form.division_four.label_tag }}
                            {% render_field form.division_four class="form-control" %}
                          </div>
                        </div>
                        <div class="col">
                          <div class="form-group">
                            {{ form.division_zero.label_tag }}
                            {% render_field form.division_zero class="form-control" %}
                          </div>
                        </div>
                      </div>
                    </div>
                    
                    {% if form.instance.pk %}
                      {% render_field form.DELETE class="form-check-input" %}
                      <!-- <label class="form-check-label" for="delete">
						              {% trans "Delete" %}
                      </label> -->
                    {% endif %}
                  </div>
                  {% endfor %}
                </fieldset> 
            

              <div class="card-footer">
                <button type="submit" class="btn btn-info">
                  <i class="fa fa-save mr-2"></i>
                  Submit</button>
              </div>
            </form>
          </div>
   
        </div>
      </div>
</div>

{% endblock %}

{% block javascript %}

<script type="text/javascript" src="{% static 'dashboard/js/jquery.formset.js' %}"></script>

<script>
    $('.myformset').formset({
        addText: '<i class="fas fa-plus-circle mr-2"></i>{% trans "Add Exam Results" %}',
		    addCssClass: 'btn btn-success',
		    deleteCssClass: 'text-danger m-2',
        deleteText: '<i class="fas fa-times-circle"></i>',
		    prefix: '{{ formset.prefix }}',
    });
</script>

<script>
  $("#id_region").change(function () {
    var url = $("#SchoolForm").attr("data-district-url");
    var regionId = $(this).val();
    $.ajax({                       
      url: url,
      data: {
        'region': regionId
      },
      success: function (data) {
        $("#id_district").html(data); 
      }
    });

  });
</script>

<!-- <script>
  $(document).ready(function () {
    $('#project-id').change(function () {
      var url = $('#form-id').attr('data-url');
      console.log(url);

      var projectID = $('#project-id').val();
      console.log(projectID);

      $.ajax({
      url: url,
      data: {
        'projectID':projectID,
      },
      type: 'GET',
      success: function(data) {
        alert();
      },
    });
  });
});
</script> -->

{% endblock javascript %}

admins/templates/admins/create_subject_groups.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header bg-primary text-light">
    <h4 class="modal-title">Create Subject Groups</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Create</button>
  </div>

</form>

admins/templates/admins/more_info_request.html
{% extends 'dashboard/base.html' %}

{% block title %}School List{% endblock %}

{% block content %}
<section class="content">
    <div class="container-fluid" style="padding-top: 40px;">
      <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header bg-info text-light">
                      <h3 class="card-title">More info request</h3>
                    </div>
                    <div class="card-body">
                      <table id="example1" class="table table-sm table-bordered">
                        <thead>
                        <tr class="bg-info text-light">
                            <th>No.</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>IP Address</th>
                            <th>School List</th>
                            <th>Search Keywords</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for s in qs %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{s.name|capfirst}}</td>
                                <td>{{s.phone}}</td>
                                <td>{{s.ip}}</td>
                                <td>
                                    <button type="button" id="read-school-{{s.id}}" class="bs-modal btn btn-sm btn-primary" data-form-url="{% url 'admins:read_school' s.pk %}">
                                        <span class="fa fa-eye"></span>
                                      </button>
                                </td>
                                <td>
                                    <button type="button" id="read-search-{{s.id}}" class="bs-modal btn btn-sm btn-info" data-form-url="{% url 'admins:read_search' s.pk %}">
                                        view keywords
                                      </button>
                                </td>
                                <td>
                                    {% if s.status == True %}
                                        <span class="badge bg-success">Already Sent</span>
                                    {% else %} 
                                    <span class="badge bg-warning">Pending</span>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if s.status == True %}
                                    {% else %}
                                    <a class="btn btn-secondary btn-sm" href="{% url 'admins:change_request_status' s.id %}">Change status</a>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</section>

<!-- Modal 1 with id="create-book"-->
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
  </div>
  
  <!-- Modal 2 with id="modal" -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

{% endblock %}

{% block javascript %}
<script type="text/javascript">
    $(function () {
  
      // Read book buttons
      $("button[id]").each(function () {
          $(this).modalForm({formURL: $(this).data("form-url")});
      });
  
    });
  </script>

<script>
	$(function () {
	  $("#example1").DataTable({
		"responsive": true, "lengthChange": false, "autoWidth": false,
	  }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
	  $('#example2').DataTable({
		"paging": true,
		"lengthChange": false,
		"searching": false,
		"ordering": true,
		"info": true,
		"autoWidth": false,
		"responsive": true,
	  });
	});
  </script>


{% endblock javascript %}

admins/templates/admins/subject_group_list.html
{% extends 'dashboard/base.html' %}

{% block content %}

    <div class="container pt-3 pb-5">
        <div class="card">
            <div class="card-header border-bottom border-info">
                <h3 class="text-title">School Subjects Groups</h3>
            </div>
            <div class="card-body">
                <div class="float-right pb-2">
                    <button id="create-book" class="btn btn-primary btn-md" type="button" name="button"><i class="fas fa-plus-circle mr-2"></i> Create Subject Group</button>
                </div>
                <div id="table">
                    <table class="table table-sm table-bordered">
                        <thead class="bg-primary text-light">
                            <tr>
                                <th>No.</th>
                                <th>Subject group</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for s in subjects %}
                            <tr>
                                <td>{{forloop.counter}}.</td>
                                <td>{{s.name}}</td>
                                <td>
                                    <button type="button" id="update-book" class="bs-modal btn btn-sm btn-primary" data-form-url="{% url 'admins:update_subject' s.pk %}">
                                        <span class="fas fa-pencil-alt"></span>
                                    </button>
                                    <button type="button" id="delete-book" class="bs-modal btn btn-sm btn-danger" data-form-url="{% url 'admins:delete_subject' s.pk %}">
                                        <span class="fa fa-trash"></span>
                                      </button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

<!-- Modal 1 with id="create-book"-->
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

<!-- Modal 2 with id="modal" -->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

{% endblock %}

{% block javascript %}
<script type="text/javascript">
    $(function () {
  
      // Update, Read and Delete book buttons open modal with id="modal" (default)
      // The formURL is retrieved from the data of the element
      $(".bs-modal").each(function () {
        $(this).modalForm({
            formURL: $(this).data('form-url')
        });
      });
  
       // Create book button opens form in modal with id="create-modal"
      $("#create-book").modalForm({
          formURL: "{% url 'admins:create_subject' %}",
          modalID: "#create-modal"
      });
  
    });
  </script>
{% endblock javascript %}